version: '3.7'

services:

  sample:
    container_name: devspotbackend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3200:3200
    environment:
      - CHOKIDAR_USEPOLLING=true
